services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: change-me
      KC_HOSTNAME: https://auth.example.com
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change-me
      KC_HEALTH_ENABLED: "true"
      JAVA_OPTS_APPEND: "-Djava.net.preferIPv4Stack=true"
    depends_on:
      - postgres
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: change-me
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: overlay
    attachable: true
