version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"  # Expose metrics endpoint
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "status"]
      interval: 15s
      timeout: 2s
      retries: 15
      start_period: 30s
    command: ["start-dev", "--http-port", "8080", "--https-port", "8443"]
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring_network
    depends_on:
      - keycloak

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - monitoring_network
    depends_on:
      - prometheus

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
